### ISSUE TITLE
cURL error 0: The cURL request was retried 3 times and did not succeed

### ISSUE THREAD

**Issue by shirne** [w7corp/easywechat#2045]
## 我用的环境

* PHP 版本：5.5.30
* overtrue/wechat 版本：3.3.34
* 是否使用了框架？框架名称：ThinkPHP 3.2

### 报错信息
```
:(

cURL error 0: The cURL request was retried 3 times and did not succeed. The most likely reason for the failure is that cURL was unable to rewind the body of the request and subsequent retries resulted in the same error. Turn on the debug option to see what went wrong. See https://bugs.php.net/bug.php?id=47204 for more information. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
错误位置
FILE: /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php 　LINE: 201

TRACE
#0 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(537): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(152): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Array)
#2 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#4 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(542): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#5 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(152): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Array)
#6 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#7 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#8 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(542): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(152): GuzzleHttp\Handler\CurlFactory::retryFailedRewind(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Array)
#10 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#11 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#12 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#13 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#14 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#15 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#16 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#17 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#18 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#19 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Client.php(352): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#20 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#21 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Client->requestAsync('GET', 'https://api.wei...', Array)
#22 /www/users/H10105784/vendor/overtrue/wechat/src/Core/Http.php(245): GuzzleHttp\Client->request('GET', 'https://api.wei...', Array)
#23 /www/users/H10105784/vendor/overtrue/wechat/src/Core/Http.php(104): EasyWeChat\Core\Http->request('https://api.wei...', 'GET', Array)
#24 /www/users/H10105784/vendor/overtrue/wechat/src/Core/AccessToken.php(240): EasyWeChat\Core\Http->get('https://api.wei...', Array)
#25 /www/users/H10105784/vendor/overtrue/wechat/src/Core/AccessToken.php(119): EasyWeChat\Core\AccessToken->getTokenFromServer()
#26 /www/users/H10105784/vendor/overtrue/wechat/src/Core/AbstractAPI.php(187): EasyWeChat\Core\AccessToken->getToken()
#27 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/RetryMiddleware.php(70): EasyWeChat\Core\AbstractAPI->EasyWeChat\Core\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#28 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Middleware.php(132): GuzzleHttp\RetryMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#29 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#30 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#31 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#32 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#33 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#34 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Client.php(352): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#35 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Client.php(162): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#36 /www/users/H10105784/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Client->requestAsync('GET', 'https://api.wei...', Array)
#37 /www/users/H10105784/vendor/overtrue/wechat/src/Core/Http.php(245): GuzzleHttp\Client->request('GET', 'https://api.wei...', Array)
#38 /www/users/H10105784/vendor/overtrue/wechat/src/Core/Http.php(104): EasyWeChat\Core\Http->request('https://api.wei...', 'GET', Array)
#39 [internal function]: EasyWeChat\Core\Http->get('https://api.wei...', Array)
#40 /www/users/H10105784/vendor/overtrue/wechat/src/Core/AbstractAPI.php(149): call_user_func_array(Array, Array)
#41 /www/users/H10105784/vendor/overtrue/wechat/src/Js/Js.php(112): EasyWeChat\Core\AbstractAPI->parseJSON('get', Array)
#42 /www/users/H10105784/vendor/overtrue/wechat/src/Js/Js.php(133): EasyWeChat\Js\Js->ticket()
#43 /www/users/H10105784/vendor/overtrue/wechat/src/Js/Js.php(71): EasyWeChat\Js\Js->signature()
#44 /www/users/H10105784/vendor/overtrue/wechat/src/Js/Js.php(93): EasyWeChat\Js\Js->config(Array, false, false, false)
#45 /www/users/H10105784/Application/Home/Controller/BaseController.class.php(143): EasyWeChat\Js\Js->getConfigArray(Array)
#46 /www/users/H10105784/Application/Home/Controller/BaseController.class.php(26): Home\Controller\BaseController->checkPlatform()
#47 /www/users/H10105784/ThinkPHP/Library/Think/Controller.class.php(41): Home\Controller\BaseController->_initialize()
#48 /www/users/H10105784/ThinkPHP/Common/functions.php(682): Think\Controller->__construct()
#49 /www/users/H10105784/ThinkPHP/Library/Think/App.class.php(89): controller('Index', '')
#50 /www/users/H10105784/ThinkPHP/Library/Think/App.class.php(202): Think\App::exec()
#51 /www/users/H10105784/ThinkPHP/Library/Think/Think.class.php(120): Think\App::run()
#52 /www/users/H10105784/ThinkPHP/ThinkPHP.php(97): Think\Think::start()
#53 /www/users/H10105784/index.php(30): require('/www/users/H101...')
#54 {main}

ThinkPHP3.2.3 { Fast & Simple OOP PHP Framework } -- [ WE CAN DO IT JUST THINK ]
```
### 其它信息
因网站备案在新一代，，所以只能买新一代的主机
虚拟主机:https://www.gzidc.com/FrontHost/details/product/base-2.html
php版本只能设置 5.2, 5.4, 5.5三个版本，当前设置 5.5
无法配置php.ini，在微信配置中设置了cacert
```
new Application([
    ....
    'guzzle' => [
                'timeout' => 3.0, // 超时时间（秒）
                'verify' => APP_PATH.'Common/Conf/cacert.pem',
            ],
]);
```

查看http缓存目录，请求结果返回是正确的( json数据 )

单独调用guzzlehttp请求微信接口返回是正确的
```
$client = new \GuzzleHttp\Client();

$response = $client->get('https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET');

echo $response->getBody()->getContents();
```
输出结果：
{"errcode":40013,"errmsg":"invalid appid rid: 6049888a-335e1e28-7484c551"}
替换正确的appid和secret：
{"access_token":"43_KSZVjitXN******AKN","expires_in":7200}

**Comment by overtrue** [comment]
看了一圈应该是 PHP 版本和 guzzle 不兼容的问题（和这个bug有关：https://bugs.php.net/bug.php?id=47204），建议升级到新的版本，

**Comment by shirne** [comment]
感谢大佬的回复，我试下切换guzzle版本能不能解决问题。

**Comment by shirne** [comment]
指定了guzzle版本6.5.5可以用了
