### ISSUE TITLE
EasyWeChat.EMERGENCY: Unable to create configured logger

### ISSUE THREAD

**Issue by singi2016cn** [w7corp/easywechat#2046]
## 我用的环境

* PHP 版本：7.4.13
* overtrue/wechat 版本：5.4
* 是否使用了框架？框架名称：laravel8.12

## 问题及现象

支付后，查看日志 /tmp/easywechat/easywechat.log

报错如下

```php
#0 /data/wwwroot/xxx/vendor/overtrue/wechat/src/Kernel/Log/LogManager.php(135): EasyWeChat\\Kernel\\Log\\LogManager->resolve()
#1 /data/wwwroot/xxx/vendor/overtrue/wechat/src/Kernel/Log/LogManager.php(120): EasyWeChat\\Kernel\\Log\\LogManager->get()
#2 /data/wwwroot/xxx/vendor/overtrue/wechat/src/Kernel/Log/LogManager.php(591): EasyWeChat\\Kernel\\Log\\LogManager->driver()
#3 /data/wwwroot/xxx/vendor/guzzlehttp/guzzle/src/Middleware.php(204): EasyWeChat\\Kernel\\Log\\LogManager->log()
#4 /data/wwwroot/xxx/vendor/guzzlehttp/promises/src/FulfilledPromise.php(41): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#5 /data/wwwroot/xxx/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\FulfilledPromise::GuzzleHttp\\Promise\\{closure}()
#6 /data/wwwroot/xxx/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Promise\\TaskQueue->run()
#7 /data/wwwroot/xxx/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#8 /data/wwwroot/xxx/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 /data/wwwroot/xxx/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#10 /data/wwwroot/xxx/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#11 /data/wwwroot/xxx/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Promise\\Promise->wait()
#12 /data/wwwroot/xxx/vendor/overtrue/wechat/src/Kernel/Traits/HasHttpRequests.php(156): GuzzleHttp\\Client->request()
#13 /data/wwwroot/xxx/vendor/overtrue/wechat/src/Payment/Kernel/BaseClient.php(95): EasyWeChat\\Payment\\Kernel\\BaseClient->performRequest()
#14 /data/wwwroot/xxx/vendor/overtrue/wechat/src/Payment/Order/Client.php(53): EasyWeChat\\Payment\\Kernel\\BaseClient->request()
#15 /data/wwwroot/xxx/app/Http/Controllers/WechatPay.php(98): EasyWeChat\\Payment\\Order\\Client->unify()
#16 /data/wwwroot/xxx/app/Http/Livewire/Index/Product.php(56): App\\Http\\Controllers\\WechatPay::getPayQrcode()
#17 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\Index\\Product->showQrcode()
#18 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#20 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#21 /data/wwwroot/xxx/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\\Container\\BoundMethod::call()
#22 /data/wwwroot/xxx/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(19): Livewire\\Component->callMethod()
#23 /data/wwwroot/xxx/vendor/livewire/livewire/src/LifecycleManager.php(70): Livewire\\HydrationMiddleware\\PerformActionCalls::hydrate()
#24 /data/wwwroot/xxx/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(12): Livewire\\LifecycleManager->hydrate()
#25 /data/wwwroot/xxx/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(19): Livewire\\Connection\\ConnectionHandler->handle()
#26 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#27 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#28 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#29 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Routing\\Route->run()
#30 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#31 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#33 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#35 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#37 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#39 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#41 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#42 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#44 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#46 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Pipeline\\Pipeline->then()
#48 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\\Routing\\Router->runRouteWithinStack()
#49 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#50 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#51 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#52 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#53 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#55 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#57 /data/wwwroot/xxx/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#59 /data/wwwroot/xxx/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#61 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#63 /data/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#64 /data/wwwroot/xxx/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#65 {main}
"}
```

**Comment by bin918** [comment]
这个问题是你传的config没有配置log

**Comment by singi2016cn** [comment]
谢谢。
