### ISSUE TITLE
使用独立的中间件类，微信回复消息出现公众号服务故障提示

### ISSUE THREAD

**Issue by hihuangwei** [w7corp/easywechat#2367]
## 我用的环境

* PHP 版本：8.0.9
* overtrue/wechat 版本：6.0-beta16
* 是否使用了框架？框架名称：Laravel 9.0

## 问题及现象

![微信截图_20220215203247](https://user-images.githubusercontent.com/3166799/154063082-355995e2-9c9f-412c-aa23-5db46396bce1.png)

![微信截图_20220215203605](https://user-images.githubusercontent.com/3166799/154063249-ea5df9b6-d753-4350-a730-b65c792268d9.png)

**Comment by overtrue** [comment]
你自行调试一下，看看最终返回的是啥: `$server->serve();` 的结果

**Comment by hihuangwei** [comment]
@overtrue 
````
[2022-02-16 13:04:21] local.ERROR: Call to undefined function App\Http\Controllers\Server\WeChat\TextMessageHandler() {"exception":"[object] (Error(code: 0): Call to undefined function App\\Http\\Controllers\\Server\\WeChat\\TextMessageHandler() at /data/wwwroot/mpms/vendor/w7corp/easywechat/src/Kernel/Traits/InteractWithHandlers.php:62)
[stacktrace]
#0 /data/wwwroot/mpms/vendor/w7corp/easywechat/src/Kernel/Traits/InteractWithHandlers.php(65): EasyWeChat\\OfficialAccount\\Server->EasyWeChat\\Kernel\\Traits\\{closure}()
#1 /data/wwwroot/mpms/vendor/w7corp/easywechat/src/OfficialAccount/Server.php(51): EasyWeChat\\OfficialAccount\\Server->handle()
#2 /data/wwwroot/mpms/app/Http/Controllers/Server/WeChat/MessageController.php(36): EasyWeChat\\OfficialAccount\\Server->serve()
#3 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Server\\WeChat\\MessageController->index()
#4 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#5 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#7 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\\Routing\\Route->run()
#8 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#9 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#11 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#13 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#14 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#15 /data/wwwroot/mpms/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#17 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /data/wwwroot/mpms/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#19 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#20 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#22 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(701): Illuminate\\Routing\\Router->runRouteWithinStack()
#23 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Router->runRoute()
#24 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\\Routing\\Router->dispatchToRoute()
#25 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#26 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#27 /data/wwwroot/mpms/app/Http/Middleware/AccessLog.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\AccessLog->handle()
#29 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#31 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#32 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#34 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#35 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#37 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#39 /data/wwwroot/mpms/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#41 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#43 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustHosts.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustHosts->handle()
#45 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#47 /data/wwwroot/mpms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#48 /data/wwwroot/mpms/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#49 {main}
"} 

````

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/releases/tag/6.0-beta17 试试看

**Comment by hihuangwei** [comment]
> https://github.com/w7corp/easywechat/releases/tag/6.0-beta17 试试看

可以了
