### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by jiangslee** [w7corp/easywechat#2476]
## 我用的环境

* PHP 版本：8.0.17
* overtrue/wechat 版本：6.x-dev(7cacf3b6)
* 是否使用了框架？框架名称：laravel 9.x

## 问题及现象
```php
$data = [
            'scene' => request('scene', 'foo=bar'),
            'env_version' => 'trial',
];
$res = $client->postJson('wxa/getwxacodeunlimit', $data);
return $res;
```
postJson获取小程序时，报错提示`Malformed UTF-8 characters, possibly incorrectly encoded for`，查阅微信文档发现返回是`返回的图片 Buffer`，由于sdk的Response默认toArray()，导致出现下述报错。
```
Symfony\Component\HttpClient\Exception\JsonException: Malformed UTF-8 characters, possibly incorrectly encoded for "https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=57_OIsCm42mAlQM9...". in file /Users/jiangslee/php/laravel/laravel-app/vendor/symfony/http-client/Response/CommonResponseTrait.php on line 94

#0 /Users/jiangslee/php/laravel/laravel-app/vendor/w7corp/easywechat/src/Kernel/HttpClient/Response.php(104): Symfony\Component\HttpClient\Response\CurlResponse->toArray(true)
#1 /Users/jiangslee/php/laravel/laravel-app/vendor/w7corp/easywechat/src/Kernel/HttpClient/Response.php(159): EasyWeChat\Kernel\HttpClient\Response->toArray(true)
#2 /Users/jiangslee/php/laravel/laravel-app/vendor/w7corp/easywechat/src/Kernel/HttpClient/Response.php(205): EasyWeChat\Kernel\HttpClient\Response->toJson()
#3 /Users/jiangslee/php/laravel/laravel-app/vendor/symfony/http-foundation/Response.php(391): EasyWeChat\Kernel\HttpClient\Response->__toString()
#4 /Users/jiangslee/php/laravel/laravel-app/vendor/laravel/framework/src/Illuminate/Http/Response.php(72): Symfony\Component\HttpFoundation\Response->setContent(Object(EasyWeChat\Kernel\HttpClient\Response))
#5 /Users/jiangslee/php/laravel/laravel-app/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent(Object(EasyWeChat\Kernel\HttpClient\Response))
#6 /Users/jiangslee/php/laravel/laravel-app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(833): Illuminate\Http\Response->__construct(Object(EasyWeChat\Kernel\HttpClient\Response), 200, Array)

```

## 期望

希望sdk得到接口为流返回时，默认toStream进行流下载？或者抛出提示开发者需要使用toDataUrl或者saveAs的方法？？

**Comment by jiangslee** [comment]
![image](https://user-images.githubusercontent.com/27892476/169765571-d38b672b-4d5f-4222-8027-3a45a7f713f2.png)
@overtrue 这个是忘了发版吗？？

**Comment by overtrue** [comment]
https://easywechat.com/6.x/client.html#%E5%A4%84%E7%90%86%E5%93%8D%E5%BA%94

```php
return $response->toPsrResponse();
```

**Comment by uniquespider** [comment]
这怎么就解决了啊，麻烦再说细一点或者贴完整代码，拜托了

**Comment by uniquespider** [comment]
谁能帮我看一下啊，请求或者response我换了好多写法，都还是这个问题
<img width="1037" alt="image" src="https://github.com/w7corp/easywechat/assets/26062592/cae2abef-85d3-42ca-a6bb-87021319c490">

**Comment by uniquespider** [comment]
非常感谢，我已经解决了
![image](https://github.com/w7corp/easywechat/assets/26062592/9272a11a-8c68-49d5-9c63-3c1272ca9b67)

**Comment by Hi9909** [comment]
使用->toStream()后，再使用->saveAs();提示找不到saveAs回调资源
