### ISSUE TITLE
Support\Arr.php::exists(array $array,string|int $key)中强制第一个参数是array，但get调用时$array为string或null，请尽快修复下

### ISSUE THREAD

**Issue by millsguo** [w7corp/easywechat#2743]
## 我用的环境

* PHP 版本：8.1.23
* overtrue/wechat 版本：6.12.9
* 是否使用了框架？框架名称：ZendFramework 1

## 问题及现象
getClient()方法，报错，错误信息如下
```
EasyWeChat\Kernel\Support\Arr::exists(): Argument #1 ($array) must be of type array, null given, called in /data/web/vendor/w7corp/easywechat/src/Kernel/Support/Arr.php on line 33



#0 /data/web/vendor/w7corp/easywechat/src/Kernel/Support/Arr.php(33): EasyWeChat\Kernel\Support\Arr::exists()
#1 /data/web/vendor/w7corp/easywechat/src/Kernel/Config.php(52): EasyWeChat\Kernel\Support\Arr::get()
#2 /data/web/vendor/w7corp/easywechat/src/OfficialAccount/Application.php(223): EasyWeChat\Kernel\Config->get()
#3 /data/web/vendor/w7corp/easywechat/src/Kernel/Traits/InteractWithClient.php(16): EasyWeChat\OfficialAccount\Application->createClient()
```

相关源码
```
public static function get(mixed $array, string|int|null $key, mixed $default = null): mixed
    {
        if (! is_array($array)) {
            return $default;
        }

        if (is_null($key)) {
            return $array;
        }

        if (static::exists($array, $key)) {
            return $array[$key];
        }

        foreach (explode('.', (string) $key) as $segment) {
            /** @phpstan-ignore-next-line */
            if (static::exists($array, $segment)) { //这里第二次$array不是数组就报错了
                /** @phpstan-ignore-next-line */
                $array = $array[$segment];
            } else {
                return $default;
            }
        }

        return $array;
    }
```
static::exists($array,$segment)，方法强制要求第一个参数是array，但有可能是string或null，这里请尽快修复下

**Comment by overtrue** [comment]
https://github.com/w7corp/easywechat/blob/6.x/src/Kernel/Support/Arr.php#L17 代码没问题，最新的版本也没问题，你安装的版本有问题，检查一下你的 composer 源。

**Comment by overtrue** [comment]
脱敏贴一下你的配置

**Comment by overtrue** [comment]
@millsguo https://github.com/w7corp/easywechat/releases/tag/6.12.10

**Comment by overtrue** [comment]
试试看
